<a href="https://colab.research.google.com/github/yasrasyeda999/My-AI-course/blob/main/Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = 4
print(x)

4


In [ ]:
import numpy as np
a = np.array([1,2,3,4,])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:

b = np.array([[2,3,3],[5,56,5]])
print(b)
print(type(b))

[[ 2  3  3]
 [ 5 56  5]]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([[1,123,12,3,12,],[2,2,2,2,2],[12,12,1,2,12]])
print(a)
print(type(a))

[[  1 123  12   3  12]
 [  2   2   2   2   2]
 [ 12  12   1   2  12]]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([[[1,12,2,3],[2,23,33,3],[23,2323,23,233],[3,23,2,3]]])
print(a)
print(type(a))

[[[   1   12    2    3]
  [   2   23   33    3]
  [  23 2323   23  233]
  [   3   23    2    3]]]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
c = np.array([[1,2,3],[1,1,1],[1,11,1],[1,1,1]])
print(c)

[[ 1  2  3]
 [ 1  1  1]
 [ 1 11  1]
 [ 1  1  1]]


In [11]:
c.ndim

2

In [13]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [14]:
np.identity(45)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a = np.array([[[[1,2,2],[3,4,4]],[[1,2,3],[1,1,1]]]])
print(a)

[[[[1 2 2]
   [3 4 4]]

  [[1 2 3]
   [1 1 1]]]]


In [ ]:
c = np.array([[[[1,2,2],[1,1,1]],[[1,1,1],[1,1,1]]]])
print(a)

[[[[1 2 2]
   [3 4 4]]

  [[1 2 3]
   [1 1 1]]]]


In [ ]:
c = np.array([[[[1,2,2],[1,1,1]],[[1,1,1],[1,1,1]]]])
print(c)

[[[[1 2 2]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]]


In [ ]:
#we can also change data type of the array
a = np.array([1,2,7.0],dtype = (bool))


In [ ]:
print(a)

[ True  True  True]


In [ ]:
a = np.array([1,2,3,45], dtype = complex)
print(a)

[ 1.+0.j  2.+0.j  3.+0.j 45.+0.j]


In [ ]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#works like range function as in python
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
#reshape(rows,columns)
np.arange(1,91).reshape(10,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((4,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.random.random((3,11))

array([[0.84071361, 0.78913054, 0.32962649, 0.0185772 , 0.84875783,
        0.71326116, 0.99104644, 0.81067192, 0.946581  , 0.65905391,
        0.17002739],
       [0.14117343, 0.36633053, 0.34416454, 0.69790494, 0.41627262,
        0.5909932 , 0.87257063, 0.55714529, 0.68045074, 0.03804538,
        0.64183656],
       [0.65621414, 0.02407739, 0.44273073, 0.38470895, 0.50216291,
        0.71444865, 0.26861929, 0.19832165, 0.33719405, 0.39836884,
        0.30954933]])

In [ ]:
#np.linspace named as linearly spaced linearly separated points banata h jo range hm usay detay hain
#np.linspace(lower range,upper range,number of items u want to generate)
np.linspace(-12,12,14)

array([-12.        , -10.15384615,  -8.30769231,  -6.46153846,
        -4.61538462,  -2.76923077,  -0.92307692,   0.92307692,
         2.76923077,   4.61538462,   6.46153846,   8.30769231,
        10.15384615,  12.        ])

In [ ]:
# can create identity matrixes by using this type of array functions
np.identity(11)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.arange(32).reshape(2,2,2,2,2)

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [ ]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(32).reshape(2,2,2,2,2)

In [ ]:
#ndim to check of dimension the array
#number of dimension of matrix is 2 always

a3.ndim



5

In [ ]:
#shape tells us about the matrix number of rows and columns
a1.shape


(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
a3.shape

(2, 2, 2, 2, 2)

In [ ]:
print(a3.shape)
a3

(2, 2, 2, 2, 2)


array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [ ]:
#size tells us about number of items
a3.size
print(a3.size)
a3

32


array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [ ]:
#item.size hr item memory mai ktna space occupy kr rha h
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [ ]:
# int 32 takes 4 bytes & int 64 takes 8 bytes
a1.itemsize

4

In [ ]:
#dtype tells the data type of the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


In [ ]:
#astype is use to change data type for example from float to float like age 34.4 can be converted to int like 34 and it contain less space
a3

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]], dtype=int32)

Array operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#scalar can perform all arithmetic operations
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
#relational can check any camparison such as(< , > , == , !=)
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 12

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a2 > 24

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations vector is basically a tensor
a1 * a2


array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Functions


In [ ]:
import numpy as np
np.max(a1)

np.int64(11)

In [ ]:
np.min(a2)

np.int64(12)

In [ ]:
np.prod(a1)

np.int64(0)

In [ ]:
np.sum(a3)

np.int64(496)

In [ ]:
#if u want to take elements from one row or column then u can do like this
#0 -> column and 1 -> row
np.max(a1,axis =0)

array([ 8,  9, 10, 11])

In [ ]:
np.min(a2,axis = 1)

array([12, 16, 20])

In [ ]:
np.min(a2,axis = 1)

array([12, 16, 20])

In [ ]:
np.sum(a3,axis = 0)

array([[[[16, 18],
         [20, 22]],

        [[24, 26],
         [28, 30]]],


       [[[32, 34],
         [36, 38]],

        [[40, 42],
         [44, 46]]]])

In [ ]:
np.prod(a1,axis =1)

array([   0,  840, 7920])

In [ ]:
np.mean(a1,axis = 1)

array([1.5, 5.5, 9.5])

In [ ]:
np.std(a1,axis = 0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [ ]:
np.var(a1,axis = 1)

array([1.25, 1.25, 1.25])

In [ ]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [ ]:
np.cos(a2)

array([[ 0.84385396,  0.90744678,  0.13673722, -0.75968791],
       [-0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302]])

In [ ]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

NameError: name 'a3' is not defined

In [ ]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponent
np.log(a1)

/tmp/ipython-input-1314993370.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [ ]:
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
#round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[ 52.,  14., 100.],
       [ 28.,  85.,  28.]])

In [ ]:
np.random.random((2,3))*100

array([[ 8.43416369,  3.49413847, 19.55233668],
       [40.99608245, 28.36960361, 36.87298569]])

In [ ]:
#round function use krny se hmain output integer mai milta h
#isi liay hm round function ka use krty hain oper waly 2 programs usi se related h or ye nearest integer pe round off krta h or float peechay walay number pe krta h
#ceil bhi agay walay integer pe krta h


In [ ]:
np.floor(np.random.random((2,3))*100)

array([[88., 63., 48.],
       [88., 32., 11.]])

In [ ]:
np.ceil(np.random.random((2,3))*100)

array([[40., 58., 31.],
       [69., 83., 92.]])

Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[-1]

array([ 8,  9, 10, 11])

In [ ]:
a3[1]

array([[4, 5],
       [6, 7]])

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[1]

np.int64(1)

In [ ]:
a1[-1]

np.int64(9)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,1]

np.int64(1)

In [ ]:
#accessing elements
a2[0,1]

np.int64(1)

In [ ]:
a2[ : :-1]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15]])

In [ ]:
a2

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a3

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [ ]:
a3[0,1]

array([[[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#indexing mai hm koi bhi element nikal skty hain rows or columns ka use kr ke
a2[2,3]

np.int64(23)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1]

array([[4, 5],
       [6, 7]])

In [ ]:
a3[1,1,1]

np.int64(7)

In [ ]:
a3[0,1,0]

np.int64(2)

In [ ]:
a3[0,0,0]

np.int64(0)

In [ ]:
a2[1]

array([4, 5, 6, 7])

In [ ]:
a2[1,1]

np.int64(5)

In [ ]:
a3[1]

array([[4, 5],
       [6, 7]])

In [ ]:
a3[0,1]

array([2, 3])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,1,0]

np.int64(6)

Slicing


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#for example a1 mai se apne 2,3,4,5 nikalna h tu slicing use ho ghi
a1[2:6]

array([2, 3, 4, 5])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#agar hm colon(:) ka use krty hain tu is se hmary pas puri row ya column ata h
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
#is syntax se hmaray pas row ati h
a2[1,:]

array([4, 5, 6, 7])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
# is syntax se hmaray pas column aye gha
a2[:,3]

array([ 3,  7, 11])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::4]

array([[0, 1, 2, 3]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[0:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::1]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[0]

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])